coverage_service: cobertura_xml
xcodeproj: MLSwift.xcodeproj
scheme: MLSwift
configuration: TestedConfiguration
source_directory: MLSwift
output_directory: reports
ignore:
  - MLSwiftExamples/*
  - MLSwiftTests/*
